In [1]:
import numpy as np

#### Скопіюй у нього масив кількості кліків по рекламному банеру, який ти створив(-ла) у минулому завданні.

In [5]:
ad_clicks = np.random.randint(100, 10000, 60)
ad_clicks

array([8371, 1961, 3663, 1078, 5468, 2155, 6302, 3986, 6419, 4824, 4938,
       2792, 5575, 4552, 2259, 1602, 8175, 4233, 2500, 7555, 4888, 5294,
       8052, 8539, 4278, 8333, 9160, 8718, 5264, 2246, 7852, 4144, 1731,
       6044, 3425, 2856,  683, 6372,  907, 3347, 4200, 1223, 1688, 9238,
        237, 7163, 9522, 1162, 6642, 2196, 4217, 8258, 3880, 6559, 3495,
       7149, 6228, 8042, 7694, 1738])

##### Виведи на екран кількість кліків:
* у перший день;
* в останній день;
* у перші 10 днів;
* за останній місяць.

In [6]:
ad_clicks[0]

np.int64(8371)

In [7]:
ad_clicks[-1]

np.int64(1738)

In [10]:
ad_clicks[:10]

array([8371, 1961, 3663, 1078, 5468, 2155, 6302, 3986, 6419, 4824])

In [14]:
ad_clicks[:31]

array([8371, 1961, 3663, 1078, 5468, 2155, 6302, 3986, 6419, 4824, 4938,
       2792, 5575, 4552, 2259, 1602, 8175, 4233, 2500, 7555, 4888, 5294,
       8052, 8539, 4278, 8333, 9160, 8718, 5264, 2246, 7852])