In [4]:
import numpy as np

In [29]:
my_array = np.array([[3276, 2, 3], [4, 5, 6]])

# Reshaping an array
reshaped_array = my_array.reshape((2, 3))  # Converts to a 2x3 array

# Concatenating arrays
c = np.array([7, 8, 9])
concatenated_array = np.concatenate((my_array, c))  
# Joins arrays [1, 2, 3, 4, 5, 6] and [7, 8, 9]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [27]:
concatenated_array.dtype

dtype('int64')

In [23]:
np.empty((2, 3, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [34]:
my_array = np.array([[3276, 2, 3], [4, 5, 6]])
mask = (my_array == 2) | (my_array == 3)

In [35]:
mask

array([[False,  True,  True],
       [False, False, False]])

In [36]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [46]:
arr = np.arange(32).reshape((8, 4))

In [39]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [40]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [42]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [52]:
arr1 = arr[:]

In [53]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [54]:
arr1[:] = 1

In [55]:
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [57]:
# Creating a 1-D array from a Python list
first_array = np.array([1, 0.5, -2, 4])
second_array = np.array([1, 1, -1, -1])

print(f"First array: {first_array}")
print(f"Second array: {second_array}")

First array: [ 1.   0.5 -2.   4. ]
Second array: [ 1  1 -1 -1]


In [59]:
first_part_array = np.array([1, 2, 3])
second_part_array = np.array([4, 5, 6])

print(np.concatenate((first_part_array, second_part_array)))

[1 2 3 4 5 6]


In [61]:
# types of elements
first_array.dtype, second_array.dtype


(dtype('float64'), dtype('int64'))

In [76]:


my_array = np.array([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], 
                  [[1, 2, 3, 4],[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])


In [77]:
my_array.shape

(3, 3, 4)

In [78]:
my_array

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])