In [89]:
import numpy as np
rng = np.random.default_rng(seed=12345)

In [29]:
my_array = np.array([[3276, 2, 3], [4, 5, 6]])

# Reshaping an array
reshaped_array = my_array.reshape((2, 3))  # Converts to a 2x3 array

# Concatenating arrays
c = np.array([7, 8, 9])
concatenated_array = np.concatenate((my_array, c))  
# Joins arrays [1, 2, 3, 4, 5, 6] and [7, 8, 9]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [27]:
concatenated_array.dtype

dtype('int64')

In [23]:
np.empty((2, 3, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [34]:
my_array = np.array([[3276, 2, 3], [4, 5, 6]])
mask = (my_array == 2) | (my_array == 3)

In [35]:
mask

array([[False,  True,  True],
       [False, False, False]])

In [36]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [46]:
arr = np.arange(32).reshape((8, 4))

In [39]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [40]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [42]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [52]:
arr1 = arr[:]

In [53]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [54]:
arr1[:] = 1

In [55]:
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [57]:
# Creating a 1-D array from a Python list
first_array = np.array([1, 0.5, -2, 4])
second_array = np.array([1, 1, -1, -1])

print(f"First array: {first_array}")
print(f"Second array: {second_array}")

First array: [ 1.   0.5 -2.   4. ]
Second array: [ 1  1 -1 -1]


In [59]:
first_part_array = np.array([1, 2, 3])
second_part_array = np.array([4, 5, 6])

print(np.concatenate((first_part_array, second_part_array)))

[1 2 3 4 5 6]


In [61]:
# types of elements
first_array.dtype, second_array.dtype


(dtype('float64'), dtype('int64'))

In [76]:


my_array = np.array([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], 
                  [[1, 2, 3, 4],[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])


In [77]:
my_array.shape

(3, 3, 4)

In [78]:
my_array

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [79]:
my_matrix = np.array(range(10, 121, 10)).reshape((3, 4)) # used the 'reshape' method to transform a vector into a matrix
print(my_matrix)


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [80]:
my_matrix[:, 0]

array([10, 50, 90])

In [81]:
players_height_weight = np.array([[175, 80], [181, 82], [179, 75], [185, 90], [184, 79]])


In [83]:
players_height_weight

2

In [87]:
tall_players = players_height_weight[:, 0] > 180 # mask
players_height_weight[tall_players] # sampling the second column and those rows that match the mask condition


array([[181,  82],
       [185,  90],
       [184,  79]])

In [86]:
tall_players

array([False,  True, False,  True,  True])

In [91]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

In [92]:
np.add(x, y)

array([ 1.14990246, -3.2095312 ,  2.92326717,  2.3674759 ,  0.56291088,
        0.60249976,  0.43596617, -1.68227225])

In [93]:
x

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [94]:
y

array([ 0.78884434, -1.25666813,  0.57585751,  1.39897899,  1.32229806,
       -0.29969852,  0.90291934, -1.62158273])

In [95]:
np.maximum(x, y)

array([ 0.78884434, -1.25666813,  2.34740965,  1.39897899,  1.32229806,
        0.90219827,  0.90291934, -0.06068952])

In [108]:
random_matrix = np.random.randint(10, size=(3, 4, 3))

In [113]:
random_matrix.sum(axis=1)

array([[31, 24, 22],
       [10, 14, 11],
       [ 7, 22, 23]])

In [110]:
random_matrix

array([[[8, 8, 1],
        [6, 7, 7],
        [8, 1, 5],
        [9, 8, 9]],

       [[4, 3, 0],
        [3, 5, 0],
        [2, 3, 8],
        [1, 3, 3]],

       [[3, 7, 0],
        [1, 9, 9],
        [0, 4, 7],
        [3, 2, 7]]])

In [105]:
np.random.seed(0)
random_matrix = np.random.randint(10, size=(3, 4)) # 3x4 random number matrix
print(random_matrix)
print(f"\nSum of all elements: {random_matrix.sum()}")
print(f"Sum of each column: {random_matrix.sum(axis=0)}")
print(f"Sum of each row: {random_matrix.sum(axis=1)}")


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

Sum of all elements: 54
Sum of each column: [14 13 13 14]
Sum of each row: [11 24 19]


In [106]:
random_matrix.ndim

2

In [119]:
a = np.ones((3, 4))     # shape: (3, 4)
b = np.array([1, 2, 3, 4]) # shape: (3,)

In [120]:
a + b

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [122]:
a.ndim

2